/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DusParser;

import com.byrfb.objects.Kontenjan;
import com.byrfb.objects.KontenjanBolum;
import com.byrfb.objects.SortCriteria;
import com.byrfb.parser.ParserMain;
import org.junit.Test;

import java.io.IOException;
import java.util.ArrayList;

public class AppTest {
    @Test
    public void getNameTest() {
        String name = KontenjanBolum.Endo.getName();
        System.out.println(name);
    }


    @Test
    public void saveAllBrans() throws IOException {
        ParserMain app = new ParserMain();
        app.read();
        app.bookParse();
        KontenjanBolum[] values = KontenjanBolum.values();
        for (int i = 0; i < values.length; i++) {
            app.setBolum(values[i]);
            ArrayList<Kontenjan> reserved = app.reserve();
            Kontenjan.sortCriteria = SortCriteria.kucukPuan;
            reserved.sort(null);
            app.save(reserved);
        }
    }

}
