/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.byrfb;

import com.byrfb.connection.SocketConnection;
import org.apache.commons.cli.*;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

public class App {


    public static void main(String[] args) throws IOException {

        App app = new App();
        app.appFunc(args);


    }

    public void appFunc(String... args) throws IOException {

        CommandLine cmd = getCommandLine(args);

        String portString = cmd.getOptionValue("port");

        int port;
        try {
            port = Integer.parseInt(portString);
        } catch (Exception e) {
            port = 8080;

        }

        ServerSocket serverSocket = null;
        Socket clientSocket = null;

        try {
            //*Server 7755 portundan Client'ı dinliyor *//
            serverSocket = new ServerSocket(port);
        } catch (Exception e) {
            System.out.println("Port Hatası!");
        }
        System.out.println("SERVER BAŞLANTI İÇİN HAZIR... port = " + port);


        while (true) {

            new SocketConnection(serverSocket.accept()).start();
        }
    }

    private CommandLine getCommandLine(String[] args) {
        Options options = new Options();

        Option input = new Option("p", "port", true, "Port for Connection");
        input.setRequired(false);
        options.addOption(input);

        CommandLineParser parser = new DefaultParser();
        HelpFormatter formatter = new HelpFormatter();
        CommandLine cmd = null;

        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            formatter.printHelp("utility-name", options);

            System.exit(1);
        }
        return cmd;
    }


}
