/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    init
 * Signature: ()V
 */


/*
 * Class:     Main
 * Method:    helloWorld
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Main_helloWorld
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Main
 * Method:    getKEy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_getKEy
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    ishandled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Main_ishandled
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
