/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rfbsoft_natives_AppSound_AppSound */
#define EXAMPLE_DLL __declspec(dllexport)

#ifndef _Included_com_rfbsoft_natives_AppSound_AppSound
#define _Included_com_rfbsoft_natives_AppSound_AppSound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rfbsoft_natives_AppSound_AppSound
 * Method:    calculate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rfbsoft_natives_AppSound_AppSound_calculate
  (JNIEnv *, jobject, jint, jint);

EXAMPLE_DLL int calculate(int a , int b);

#ifdef __cplusplus
}
#endif
#endif
