/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rfbsoft_natives_AppSound_Main */

#ifndef _Included_com_rfbsoft_natives_AppSound_Main
#define _Included_com_rfbsoft_natives_AppSound_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rfbsoft_natives_AppSound_Main
 * Method:    topla
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rfbsoft_natives_AppSound_Main_topla
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_rfbsoft_natives_AppSound_Main
 * Method:    carp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rfbsoft_natives_AppSound_Main_carp
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
